services:
  migrate:
    build: .
    command: alembic -c /api/alembic.ini upgrade head
    env_file:
      - .env
    depends_on:
      - db

  newhorizons_api:
    build: .
    container_name: new_horizons_api
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - migrate
    ports:
      - "9002:9002"
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: new_horizons_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newhorizons
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: new_horizons_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: new_horizons_celery
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A app.tasks worker --loglevel=info
    restart: unless-stopped

volumes:
  pgdata:
